spring:
  application:
    name: gift_api

  datasource:
    url: jdbc:mysql://localhost:3306/giftapi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml