spring:
  application:
    name: gift_api

  datasource:
    url: jdbc:mysql://localhost:3307/gift_api
    username: mysql
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none