spring.application.name=gift_api
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:file:~/gift_api
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.sql.init.platform=h2
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.open-in-view=false
